In [ ]:
#NaiveBayesClassifier

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [ ]:
#1.Collecting data

In [2]:
data=pd.read_csv("Datasets/pacific.csv")
data.head()

,ID,Name,Date,Time,Event,Status,Latitude,Longitude,Maximum Wind,Minimum Pressure,...,Low Wind SW,Low Wind NW,Moderate Wind NE,Moderate Wind SE,Moderate Wind SW,Moderate Wind NW,High Wind NE,High Wind SE,High Wind SW,High Wind NW
0,EP011949,UNNAMED,19490611,0,,TS,20.2N,106.3W,45,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
1,EP011949,UNNAMED,19490611,600,,TS,20.2N,106.4W,45,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
2,EP011949,UNNAMED,19490611,1200,,TS,20.2N,106.7W,45,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
3,EP011949,UNNAMED,19490611,1800,,TS,20.3N,107.7W,45,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
4,EP011949,UNNAMED,19490612,0,,TS,20.4N,108.6W,45,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999

In [3]:
pre_columns=data[:]
pre_columns.drop(['ID','Name','Date','Time','Event','Status','Latitude','Longitude'],axis=1,inplace=True)
pre_columns

C:\Users\azart\AppData\Local\Temp\ipykernel_15644\3332941561.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pre_columns.drop(['ID','Name','Date','Time','Event','Status','Latitude','Longitude'],axis=1,inplace=True)

,Maximum Wind,Minimum Pressure,Low Wind NE,Low Wind SE,Low Wind SW,Low Wind NW,Moderate Wind NE,Moderate Wind SE,Moderate Wind SW,Moderate Wind NW,High Wind NE,High Wind SE,High Wind SW,High Wind NW
0,45,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
1,45,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
2,45,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
3,45,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
4,45,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26132,35,1002,60,0,0,0,0,0,0,0,0,0,0,0
26133,30,1007,0,0,0,0,0,0,0,0,0,0,0,0
26134,30,1008,0,0,0,0,0,0,0,0,0,0,0,0
26135,25,1009,0,0,0,0,0,0,0,0,0,0,0,0
26136,20,1010,0,0,0,0,0,0,0,0,0,0,0,0

In [4]:
relevant_cols=pre_columns.columns
relevant_cols

Index(['Maximum Wind', 'Minimum Pressure', 'Low Wind NE', 'Low Wind SE',
       'Low Wind SW', 'Low Wind NW', 'Moderate Wind NE', 'Moderate Wind SE',
       'Moderate Wind SW', 'Moderate Wind NW', 'High Wind NE', 'High Wind SE',
       'High Wind SW', 'High Wind NW'],
      dtype='object')

In [6]:
train,test=train_test_split(data,test_size=0.3,random_state=5)
train_X=train[relevant_cols]
train_Y=train['Status']
test_X=test[relevant_cols]
test_Y=test['Status']

In [7]:
#use the model
gnb=GaussianNB()

In [8]:
#Prediction
gnb.fit(train_X,train_Y)
predicted_gnb=gnb.predict(test_X)

In [9]:
pd.DataFrame({"Predicated":predicted_gnb,"ActualValue":test_Y}).head()

      Predicated ActualValue
10506         ET          TS
21194         SS          TS
92            ET          HU
21301         DB          LO
21668         SS          TS